### ISSUE TITLE
Running Smoothie on Linux causes a PyTaskbar error

### ISSUE THREAD

**Issue by spenduo** [couleur-tweak-tips/Smoothie#23]
When I run Smoothie on Arch Linux I get a error about comtypes from PyTaskbar. On comtypes's github it says that it only works for Windows if that means anything

`Traceback (most recent call last):
  File "/home/spen/Downloads/Smoothie/src/main.py", line 4, in <module>
    import exec
  File "/home/spen/Downloads/Smoothie/src/exec.py", line 4, in <module>
    from bar import * # Progress bar
  File "/home/spen/Downloads/Smoothie/src/bar.py", line 2, in <module>
    import PyTaskbar
  File "/home/spen/.local/lib/python3.10/site-packages/PyTaskbar/__init__.py", line 1, in <module>
    from .ProgressAPI import Progress
  File "/home/spen/.local/lib/python3.10/site-packages/PyTaskbar/ProgressAPI.py", line 3, in <module>
    import comtypes.client as cc
  File "/home/spen/.local/lib/python3.10/site-packages/comtypes/__init__.py", line 28, in <module>
    from _ctypes import COMError
ImportError: cannot import name 'COMError' from '_ctypes' (/usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so)`

**Comment by spenduo** [comment]
There's a fix in the dev branch already
